{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPZ8n0lGr5ZIt6wgcZHg3C3",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/enlightenEE2026/kingdom/blob/V1.1/3king2.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import io\n",
        "import streamlit as st\n",
        "import easyocr\n",
        "import PyPDF2\n",
        "from PIL import Image, ImageDraw, ImageFont\n",
        "from thefuzz import process, fuzz\n",
        "import numpy as np\n",
        "\n",
        "# 1. APPLICATION SETUP & PAGE LAYOUT\n",
        "st.set_page_config(layout=\"wide\", page_title=\"Image Translation Overlay Tool\")\n",
        "st.title(\"🌐 Image Translation Overlay Tool\")\n",
        "\n",
        "# 2. CACHE OCR READER (Prevents reloading on every user interaction)\n",
        "@st.cache_resource\n",
        "def load_ocr_reader():\n",
        "    # Pre-loads models for Simplified Chinese and English\n",
        "    return easyocr.Reader(['ch_sim', 'en'])\n",
        "\n",
        "try:\n",
        "    reader = load_ocr_reader()\n",
        "except Exception as ocr_init_err:\n",
        "    st.error(\"Failed to initialize EasyOCR engine. Ensure system dependencies are met.\")\n",
        "    st.stop()\n",
        "\n",
        "# 3. INTERFACE BUILDER\n",
        "st.markdown(\"### 1. Upload Files & Adjust Sensitivity\")\n",
        "\n",
        "col1, col2 = st.columns(2)\n",
        "with col1:\n",
        "    uploaded_image_file = st.file_uploader(\"Upload Image File\", type=[\"png\", \"jpg\", \"jpeg\"])\n",
        "with col2:\n",
        "    uploaded_pdf_file = st.file_uploader(\"Upload PDF Translation Dictionary\", type=[\"pdf\"])\n",
        "\n",
        "user_threshold = st.slider('Match Sensitivity %:', min_value=30, max_value=100, value=60, step=5)\n",
        "\n",
        "st.markdown(\"### 2. Execute Overlay\")\n",
        "execute_btn = st.button(\"Translate and Overlay Text\", type=\"primary\")\n",
        "\n",
        "# 4. PROCESSING PIPELINE\n",
        "if execute_btn:\n",
        "    if not uploaded_image_file:\n",
        "        st.error(\"Please upload an image file.\")\n",
        "    elif not uploaded_pdf_file:\n",
        "        st.error(\"Please upload your PDF translation file.\")\n",
        "    else:\n",
        "        with st.spinner(\"Parsing PDF dictionary and scanning image text... Please wait...\"):\n",
        "\n",
        "            # --- Stream Pointer Resets ---\n",
        "            uploaded_pdf_file.seek(0)\n",
        "            uploaded_image_file.seek(0)\n",
        "\n",
        "            translation_map = {}\n",
        "            excel_choices = []\n",
        "            valid_pdf = True\n",
        "\n",
        "            # --- 1. SAFE PDF PARSING ---\n",
        "            try:\n",
        "                pdf_reader = PyPDF2.PdfReader(io.BytesIO(uploaded_pdf_file.read()))\n",
        "                if len(pdf_reader.pages) == 0:\n",
        "                    st.error(\"❌ The uploaded PDF appears to be empty.\")\n",
        "                    valid_pdf = False\n",
        "            except Exception as e:\n",
        "                st.error(\"❌ Invalid PDF File. Please ensure you uploaded a true PDF document.\")\n",
        "                st.info(f\"Technical details: {str(e)}\")\n",
        "                valid_pdf = False\n",
        "\n",
        "            if valid_pdf:\n",
        "                try:\n",
        "                    for page in pdf_reader.pages:\n",
        "                        page_text = page.extract_text()\n",
        "                        if not page_text:\n",
        "                            continue\n",
        "\n",
        "                        for line in page_text.split('\\n'):\n",
        "                            line = line.strip()\n",
        "                            if not line:\n",
        "                                continue\n",
        "\n",
        "                            parts = []\n",
        "                            if ',' in line:\n",
        "                                parts = line.split(',', 1)\n",
        "                            elif ':' in line:\n",
        "                                parts = line.split(':', 1)\n",
        "                            else:\n",
        "                                # Find transitions between non-ASCII (Chinese) and ASCII character spaces\n",
        "                                for idx, char in enumerate(line):\n",
        "                                    if idx > 0 and ord(char) < 128 and ord(line[idx-1]) >= 128:\n",
        "                                        parts = [line[:idx].strip(), line[idx:].strip()]\n",
        "                                        break\n",
        "\n",
        "                            if len(parts) == 2:\n",
        "                                source_text = parts[0].strip()\n",
        "                                translation_text = parts[1].strip()\n",
        "\n",
        "                                if source_text and translation_text:\n",
        "                                    translation_map[source_text.lower()] = translation_text\n",
        "                                    excel_choices.append(source_text)\n",
        "\n",
        "                    if not translation_map:\n",
        "                        st.error(\"❌ Layout Parsing Error: No valid translation pairs found inside this file.\")\n",
        "                        st.info(\"💡 Ensure your PDF uses clear indicators like: '张飞, Zhang Fei' or '张飞: Zhang Fei'.\")\n",
        "                        valid_pdf = False\n",
        "\n",
        "                except Exception as e:\n",
        "                    st.error(f\"❌ Failed to extract dictionary content: {str(e)}\")\n",
        "                    valid_pdf = False\n",
        "\n",
        "\n",
        "            # --- 2. SAFE IMAGE PROCESSING & BOX OVERLAY ---\n",
        "            if valid_pdf:\n",
        "                try:\n",
        "                    original_image = Image.open(io.BytesIO(uploaded_image_file.read())).convert(\"RGBA\")\n",
        "                    base_image = original_image.copy()\n",
        "\n",
        "                    # Convert to NumPy array for EasyOCR ingestion\n",
        "                    img_np = np.array(base_image)\n",
        "                    ocr_results = reader.readtext(img_np, detail=1)\n",
        "\n",
        "                    if not ocr_results:\n",
        "                        st.warning(\"❓ No text blocks detected in this image layout.\")\n",
        "                    else:\n",
        "                        draw_layer = ImageDraw.Draw(base_image)\n",
        "                        matches_count = 0\n",
        "\n",
        "                        for box, text_raw, confidence in ocr_results:\n",
        "                            text_clean = text_raw.strip()\n",
        "                            if not text_clean or not excel_choices:\n",
        "                                continue\n",
        "\n",
        "                            # Fuzzy match extraction\n",
        "                            best_match, score = process.extractOne(\n",
        "                                text_clean,\n",
        "                                excel_choices,\n",
        "                                scorer=fuzz.token_sort_ratio\n",
        "                            )\n",
        "\n",
        "                            if score >= user_threshold:\n",
        "                                translation_text = str(translation_map[best_match.lower()])\n",
        "                                matches_count += 1\n",
        "\n",
        "                                # Extract structural dimensions\n",
        "                                x_coords = [p[0] for p in box]\n",
        "                                y_coords = [p[1] for p in box]\n",
        "                                x_min, y_min = int(min(x_coords)), int(min(y_coords))\n",
        "                                x_max, y_max = int(max(x_coords)), int(max(y_coords))\n",
        "\n",
        "                                box_width = x_max - x_min\n",
        "                                box_height = y_max - y_min\n",
        "\n",
        "                                # Solid opaque mask to wipe clean original source characters\n",
        "                                draw_layer.rectangle([x_min, y_min, x_max, y_max], fill=(15, 15, 15, 255))\n",
        "\n",
        "                                # Dynamic Font Calculation Fallback\n",
        "                                font_size = max(10, int(box_height * 0.75))\n",
        "                                try:\n",
        "                                    font = ImageFont.truetype(\"arial.ttf\", font_size)\n",
        "                                except IOError:\n",
        "                                    font = ImageFont.load_default()\n",
        "\n",
        "                                # Draw the translation centered vertically inside the mask block\n",
        "                                draw_layer.text((x_min + 4, y_min + (box_height - font_size) // 4),\n",
        "                                                translation_text, fill=(255, 255, 255, 255), font=font)\n",
        "\n",
        "                        st.success(f\"✨ Successfully replaced {matches_count} text blocks!\")\n",
        "\n",
        "                        # --- CONVERT PROCESSED IMAGE TO DOWNLOADABLE BUFFER ---\n",
        "                        # Convert to RGB to ensure clean, standardized high-res PNG serialization\n",
        "                        final_output_image = base_image.convert(\"RGB\")\n",
        "                        img_buffer = io.BytesIO()\n",
        "                        final_output_image.save(img_buffer, format=\"PNG\", quality=100)\n",
        "                        img_buffer.seek(0)\n",
        "\n",
        "                        # --- EXPORT ACTION INTERFACE ---\n",
        "                        st.markdown(\"### 3. Save Translated File\")\n",
        "                        st.download_button(\n",
        "                            label=\"💾 Download Translated High-Res PNG\",\n",
        "                            data=img_buffer,\n",
        "                            file_name=\"translated_overlay_output.png\",\n",
        "                            mime=\"image/png\",\n",
        "                            type=\"secondary\"\n",
        "                        )\n",
        "\n",
        "                        # --- DISPLAY SIDE-BY-SIDE RESULT COLS ---\n",
        "                        out_col1, out_col2 = st.columns(2)\n",
        "                        with out_col1:\n",
        "                            st.subheader(\"Original Image\")\n",
        "                            st.image(original_image, use_container_width=True)\n",
        "                        with out_col2:\n",
        "                            st.subheader(\"Translated Overlay\")\n",
        "                            st.image(base_image, use_container_width=True)\n",
        "\n",
        "                except Exception as img_err:\n",
        "                    st.error(\"❌ Invalid Image File. Please verify your uploaded file.\")\n",
        "                    st.info(f\"Technical details: {str(img_err)}\")\n",
        "\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "ghsf1_fEIdrc",
        "outputId": "ab709e10-3be3-42ce-c1d8-a5e2c3c93be5"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2026-07-14 10:33:34.373 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:34.379 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:34.387 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:34.390 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:34.408 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "WARNING:easyocr.easyocr:Neither CUDA nor MPS are available - defaulting to CPU. Note: This module is much faster with a GPU.\n",
            "2026-07-14 10:33:38.354 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.355 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.356 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.359 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.361 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.362 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.364 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.365 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.368 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.368 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.369 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.370 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.371 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.372 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.374 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.375 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.376 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.377 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.379 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.380 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.381 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.381 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.382 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.383 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.384 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.385 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.386 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.387 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-07-14 10:33:38.388 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
          ]
        }
      ]
    }
  ]
}